<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EPPlus" Version="6.1.1" />
    <PackageReference Include="QuestPDF" Version="2023.12.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZayirAlkhayr.Interface\ZayirAlkhayr.Interface.csproj" />
  </ItemGroup>

</Project>
